---

- name: Ensure jenkins_init_folder 
  file:
    path: "{{ jenkins_init_folder }}"
    state: directory
    mode: 0644

- name: Ensure jenkins service folder
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
  with_items:
    - /var/log/jenkins
    - /var/cache/jenkins

- name: Ensure jenkins_init_file
  template:
    src: override.conf.j2
    dest: "{{ jenkins_init_folder }}/override.conf"
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0644
  notify:
    - daemon reload
    - restart jenkins

- name: Ensure jenkins_home {{ jenkins_home }} exists.
  file:
    path: "{{ jenkins_home }}"
    state: directory
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: u+rwx
    follow: true

- name: Create custom init scripts directory.
  file:
    path: "{{ jenkins_home }}/init.groovy.d"
    state: directory
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0775

- name: Configure proxy config for Jenkins
  template:
    src: proxy.xml
    dest: "{{ jenkins_home }}/proxy.xml"
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0664
  when:
    - jenkins_proxy_host | length > 0
    - jenkins_proxy_port | length > 0
  notify:
    - restart jenkins

