---
- name: Ensure dependencies are installed.
  package:
    name:
      - curl
      - initscripts
      - git
      - "{{ 'libselinux-python' if ansible_python['version']['major'] < 3 else 'python3-libselinux' }}"
    state: present

- name: Add jenkins package yum repo
  yum_repository:
    name: jenkins
    description: Jenkins
    baseurl: "{{ jenkins_repo_baseurl }}"
    enabled: yes
    gpgcheck: yes
    gpgkey: "{{ jenkins_repo_key_url }}"
  register: yum_package_repo_addition
#  until: yum_package_repo_addition is succeeded
#  retries: 5
#  delay: 10

- name: Refresh yum metadata cache if repo changed.
  command: >
    yum clean metadata
    warn=no
  when: yum_package_repo_addition.changed

- name: Define the jenkins package name
  set_fact:
    jenkins_package_name: "jenkins{{ package_version_separator }}{{ jenkins_version }}"
  when: jenkins_version | default(false)

- name: Install Jenkins Package
  package:
    name: "{{ jenkins_package_name | default('jenkins') }}"
    state: present
  notify:
    - restart jenkins

