---

- name: daemon reload
  systemd:
    daemon_reload: yes
  when: ansible_os_family == 'RedHat'
    and ansible_distribution_major_version >= '7'

- name: restart jenkins
  service: name=jenkins state=restarted
